### ISSUE TITLE
Crashes the Pixel Launcher

### ISSUE THREAD

**Issue by JenyaKirmizaTripTop** [Pushwoosh/pushwoosh-android-sdk#116]
I'm using adaptive-icons for my app
When using push woosh, it created badge on app icon inside device menu.
When i am trying to open this badge by longpress it crashes the Pixel Launcher

When using my own notifications app doesn't crash, it opens without any issues

https://imgur.com/xbSEezH

Device: Pixel 2, android version 9
```
2018-11-06 15:18:28.668 24592-24592/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.apps.nexuslauncher, PID: 24592
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.isProjected()' on a null object reference
        at android.graphics.drawable.AdaptiveIconDrawable.isProjected(AdaptiveIconDrawable.java:552)
        at android.view.View.invalidateInternal(View.java:16438)
        at android.view.View.invalidate(View.java:16398)
        at android.view.View.setBackgroundDrawable(View.java:21584)
        at android.view.View.setBackground(View.java:21470)
        at com.android.launcher3.notification.NotificationMainView.applyNotificationInfo(SourceFile:129)
        at com.android.launcher3.popup.PopupPopulator.lambda$createUpdateRunnable$0(SourceFile:139)
        at com.android.launcher3.popup.-$$Lambda$PopupPopulator$mfbIeKUr23EqjgnrfxXRLYPVxyA.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by wfhm** [comment]
@JenyaKirmizaTripTop 

We were unable to reproduce the issue so far. May I ask you to create a support ticket by sending an email to help@pushwoosh.com with a link to this issue and attach a reproducer apk?

**Comment by wfhm** [comment]
@JenyaKirmizaTripTop any news on this one?

**Comment by JenyaKirmizaTripTop** [comment]
> @JenyaKirmizaTripTop any news on this one?

doesn't matter any longer. I've changed the image and it was fixed. Seems like the problem was on android side. Smth with bitmap decode

**Comment by wfhm** [comment]
@JenyaKirmizaTripTop Thank you for letting us know! If the issue comes back, just let us know.
