### ISSUE TITLE
NetworkReceiver I/O operation on main thread (Strict Mode)

### ISSUE THREAD

**Issue by rom4ek** [Pushwoosh/pushwoosh-android-sdk#117]
Hello, we noticed a lot of warnings when running an app in StrictMode regarding `NetworkReceiver` operations:

> StrictMode policy violation; ~duration=39 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65599 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:807)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:572)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:563)
        at android.app.ContextImpl.getDatabasesDir(ContextImpl.java:802)
        at android.app.ContextImpl.getDatabasePath(ContextImpl.java:781)
        at android.content.ContextWrapper.getDatabasePath(ContextWrapper.java:320)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:292)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:238)
        at com.pushwoosh.internal.network.g.a(Unknown Source:8)
        at com.pushwoosh.NetworkReceiver.onReceive(Unknown Source:33)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1313)
        at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
        at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

From what I can see here you're probably accessing SQLite database from the main thread, which leads to ANRs and would actually crash the app once you enable `penaltyDeath()` for StrictMode. Would it be possible to fix this from your side?

Also, there's one more thing with accessing SharedPreferences on the main thread, not sure how easy is this one to fix, but would be also cool:

> StrictMode: StrictMode policy violation; ~duration=32 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65599 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:807)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:572)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:563)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:519)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:714)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:368)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:167)
        at com.pushwoosh.internal.platform.prefs.c.providePrefs(Unknown Source:9)
        at com.pushwoosh.internal.utils.c.e(Unknown Source:6)
        at com.pushwoosh.internal.utils.c.f(Unknown Source:1)
        at com.pushwoosh.internal.utils.c.b(Unknown Source:9)
        at com.pushwoosh.internal.utils.c.c(Unknown Source:0)
        at com.pushwoosh.inapp.a.j.a(Unknown Source:0)
        at com.pushwoosh.inapp.a.a.a(Unknown Source:27)
        at com.pushwoosh.inapp.a.i.a(Unknown Source:10)
        at com.pushwoosh.a.n.b(Unknown Source:34)
        at com.pushwoosh.p.a(Unknown Source:2)
        at com.pushwoosh.q.onReceive(Unknown Source:4)
        at com.pushwoosh.internal.event.Emitter.emit(Unknown Source:6)
        at com.pushwoosh.internal.event.Emitter$1.b(Unknown Source:4)
        at com.pushwoosh.internal.event.a.onReceive(Unknown Source:2)
        at com.pushwoosh.internal.event.EventBus.b(Unknown Source:23)
        at com.pushwoosh.internal.event.EventBus.a(Unknown Source:0)
        at com.pushwoosh.internal.event.c.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

I've seen like 15 to 20 violations from StrictMode regarding these two operations for each app run, so I think if we eliminate them, the app performance would significantly improve (not guaranteed though).
Thanks!

**Comment by wfhm** [comment]
Fixed in 7.20.0.
