### ISSUE TITLE
Crash: No address associated with hostname

### ISSUE THREAD

**Issue by vixez** [Pushwoosh/pushwoosh-android-sdk#141]
If you start an app for the very first time (clear the storage of the app to be sure) without an internet connection, the SDK will cause the app to crash.

I replaced the app ID by xyz.

`[RequestManager] ERROR: Unable to resolve host "xyz.api.pushwoosh.com": No address associated with hostname
    com.pushwoosh.internal.network.b: Unable to resolve host "xyz.api.pushwoosh.com": No address associated with hostname
        at com.pushwoosh.internal.network.e.a(Unknown Source:174)
        at com.pushwoosh.internal.network.e.a(Unknown Source:0)
        at com.pushwoosh.internal.network.e$b.a(Unknown Source:20)
        at com.pushwoosh.internal.network.e$b.doInBackground(Unknown Source:2)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by wfhm** [comment]
Hey @vixez,

Just tried to reproduce it with the latest SDK version and it works just fine without internet connection. Could you please specify the SDK version you use and share a reproducer APK with us? You can send it via the Contact Us form. Also, can you check in the device log which particular API request fails to be sent?

**Comment by vixez** [comment]
@wfhm 
Hello,
I'm using the latest SDK (6.0.0)


[Here](https://gist.github.com/vixez/a3f3e09c9abf0477543abd41d9d8a7b4) is a gist with the full Pushwoosh log.

**Comment by wfhm** [comment]
@vixez,

Pushwoosh SDK does indeed throw this error when there is no internet connection, however, it should not crash the app. We were unable to reproduce the issue with the latest SDK so far, so it would be really useful if you could send us a reproducer APK. Is it by any chance possible?

**Comment by vixez** [comment]
@wfhm 

Hello, 
It seems like this is a Retrofit issue and not a Pushwoosh issue. I have now added an extra check before the app starts if there is internet connectivity, this solves my problem.

I will close the issue, thank you.
