### ISSUE TITLE
Crash: Missing permission to insert badges on Xiaomi MiA1

### ISSUE THREAD

**Issue by LukaKit** [Pushwoosh/pushwoosh-android-sdk#143]
We're noticing crashes on particular Xiaomi phones (Mi A1, running Android 9). From what we can tell, the crash occurs immediately after the phone receives a notification.
We are using pushwoosh and pushwoosh-inbox versions 5.22.0.

```
Fatal Exception: java.lang.SecurityException: Missing permission to insert badges
       at android.os.Parcel.createException(Parcel.java:1950)
       at android.os.Parcel.readException(Parcel.java:1918)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.insert(ContentProviderProxy.java:476)
       at android.content.ContentResolver.insert(ContentResolver.java:1590)
       at android.content.AsyncQueryHandler$WorkerHandler.handleMessage(AsyncQueryHandler.java:96)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by wfhm** [comment]
Hey @LukaKit,

Could you please confirm that 'pushwoosh-badge' lib is added to your project alongside with 'pushwoosh' and 'pushwoosh-inbox'? If so, this is really strange. By any chance could you please check your final AndroidManifest.xml and look for `permission.BROADCAST_BADGE`​? Mi A1 should be running vanilla Android, so this is the permission that is missing according to the exception message.

**Comment by LukaKit** [comment]
Thank you for your help. 
We added some changes, based on your answer, and I'll close the issue for now, because we won't be able to test it right away.
