### ISSUE TITLE
GeoLocationService crashes

### ISSUE THREAD

**Issue by januszdewel** [Pushwoosh/pushwoosh-android-sdk#15]
Hello,

I am using pushwoosh library v. 2.9.11 for Android and I have encountered following random crashes in my app.

---
<pre><code>
    java.lang.NullPointerException
           at android.location.Location.distanceTo(Location.java:428)
           at com.arellomobile.android.push.GeoLocationService.onLocationChanged()
           at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:255)
           at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:184)
           at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:200)
           at android.os.Handler.dispatchMessage(Handler.java:99)
           at android.os.Looper.loop(Looper.java:176)
           at android.app.ActivityThread.main(ActivityThread.java:5419)
           at java.lang.reflect.Method.invokeNative(Method.java)
           at java.lang.reflect.Method.invoke(Method.java:525)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
           at dalvik.system.NativeStart.main(NativeStart.java)
</code></pre>
---
<pre><code>
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.tenforwardconsulting.cordova.bgloc.SINGLE_LOCATION_UPDATE_ACTION flg=0x10 (has extras) } in com.arellomobile.android.push.GeoLocationService$1@413dedb0
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:737)
       at android.os.Handler.handleCallback(Handler.java:605)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4519)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at android.location.Location.distanceTo(Location.java:413)
       at com.arellomobile.android.push.GeoLocationService.onPollStationaryLocation()
       at com.arellomobile.android.push.GeoLocationService.access$000()
       at com.arellomobile.android.push.GeoLocationService$1.onReceive()
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:728)
       at android.os.Handler.handleCallback(Handler.java:605)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4519)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
       at dalvik.system.NativeStart.main(NativeStart.java)
    </code></pre>

---

<code><pre>
java.lang.RuntimeException: Unable to create service com.arellomobile.android.push.GeoLocationService: java.lang.RuntimeException: Init failed
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2382)
       at android.app.ActivityThread.access$1600(ActivityThread.java:131)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4754)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.RuntimeException: Init failed
       at android.media.ToneGenerator.native_setup(ToneGenerator.java)
       at android.media.ToneGenerator.<init>(ToneGenerator.java:740)
       at com.arellomobile.android.push.GeoLocationService.onCreate()
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2372)
       at android.app.ActivityThread.access$1600(ActivityThread.java:131)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4754)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
    </pre></code>

---

All of above unfortunately come from the inside of the GeoLocationService class and it does not seem that I can do anything about it in my app.

Basing on the first two stacktraces I presume that there is null Location object passed to the Location#distanceTo() method.

Regarding last stacktrace I might have found a solution here:
http://stackoverflow.com/questions/13439051/tonegenerator-crash-android/13868360

If there's more data that I should provide, please let me know.
Is there any fix that I can apply on the app's side? Perhaps above problems had been already fixed in the newest library release?

Cheers

**Comment by DimanAM** [comment]
Fixed in 2.9.15
