### ISSUE TITLE
Pushwoosh: Can't get cached resources: 

### ISSUE THREAD

**Issue by serveravt** [Pushwoosh/pushwoosh-android-sdk#154]
Every time I unlock my device, I get exception 

2021-01-25 11:44:40.515 30883-30965/**** E/SQLiteLog: (1) no such table: lockScreenResources in "SELECT * FROM lockScreenResources"
2021-01-25 11:44:40.516 30883-30965/**** E/Pushwoosh: Can't get cached resources: 
    android.database.sqlite.SQLiteException: no such table: lockScreenResources (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM lockScreenResources
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1545)
        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1392)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1263)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1431)
        at com.pushwoosh.repository.LockScreenMediaStorageImpl.c(Unknown Source:21)
        at com.pushwoosh.internal.utils.LockScreenReceiver$d.a(Unknown Source:4)
        at com.pushwoosh.internal.utils.LockScreenReceiver$d.doInBackground(Unknown Source:2)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

tested on Google Pixel, Google Pixel 3 XL

**Comment by wfhm** [comment]
@serveravt,

Will be fixed with the next release.

**Comment by wfhm** [comment]
@serveravt,

Fixed with 6.1.1.
