### ISSUE TITLE
E/Pushwoosh: You must add "implementation 'com.google.firebase:firebase-messaging:+'" line to your app build.gradle.

### ISSUE THREAD

**Issue by enricoantonini84** [Pushwoosh/pushwoosh-android-sdk#163]
Dear Pushwoosh,
I've just updated android studio to 4.2.1 and when I try to run the app on my device, I receive the following fatal error:

`2021-05-17 10:05:27.385 17378-17378/it.bantoa.bantoa E/Pushwoosh: You must add "implementation 'com.google.firebase:firebase-messaging:+'" line to your app build.gradle.
    Check documentation for more info https://goo.gl/UVJKfp
2021-05-17 10:05:27.388 17378-17378/it.bantoa.bantoa E/AndroidRuntime: FATAL EXCEPTION: main
    Process: it.bantoa.bantoa, PID: 17378
    java.lang.RuntimeException: Unable to get provider com.pushwoosh.PushwooshInitProvider: java.lang.IllegalStateException: You must add "implementation 'com.google.firebase:firebase-messaging:+'" line to your app build.gradle.
    Check documentation for more info https://goo.gl/UVJKfp
        at android.app.ActivityThread.installProvider(ActivityThread.java:7247)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6783)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6700)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: You must add "implementation 'com.google.firebase:firebase-messaging:+'" line to your app build.gradle.
    Check documentation for more info https://goo.gl/UVJKfp
        at com.pushwoosh.firebase.internal.checker.FirebaseChecker.check(Unknown Source:15)
        at com.pushwoosh.firebase.internal.registrar.FcmRegistrar.init(Unknown Source:5)
        at com.pushwoosh.notification.PushwooshNotificationManager.d(Unknown Source:2)
        at com.pushwoosh.d.a(Unknown Source:59)
        at com.pushwoosh.PushwooshPlatform.l(Unknown Source:2)
        at com.pushwoosh.PushwooshInitializer.init(Unknown Source:67)
        at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source:18)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7242)
        	... 10 more
     Caused by: java.lang.ClassNotFoundException: com.google.firebase.iid.FirebaseInstanceId
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.pushwoosh.firebase.internal.checker.FirebaseChecker.check(Unknown Source:2)
        	... 19 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[dex file "/data/data/it.bantoa.bantoa/code_cache/.overlay/base.apk/classes.dex", dex file "/data/data/it.bantoa.bantoa/code_cache/.overlay/base.apk/classes7.dex", zip file "/data/app/~~yv5-XsAipNyANq9GLSGV1w==/it.bantoa.bantoa-7EdL8u7jz8B63gCzX42baA==/base.apk"],nativeLibraryDirectories=[/data/app/~~yv5-XsAipNyANq9GLSGV1w==/it.bantoa.bantoa-7EdL8u7jz8B63gCzX42baA==/lib/arm64, /system/lib64, /system_ext/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 23 more`

It's a weird error because in my gradle I've already imported  com.google.firebase:firebase-messaging:22.0.0.
Is there any issue with the new sdks?

**Comment by wfhm** [comment]
Hi @enricoantonini84,

Can you share your build.gradle files (app: and project:)?

**Comment by YarikSOffice** [comment]
I'm facing the same issue while migrating to FCM `22.0.0` (from `21.0.1`).

I believe it has something to do with `firebase-iid` artifact which was removed in FCM `22.0.0`.

Everything works just fine If I add it back explicitly
```
implementation "com.google.firebase:firebase-iid:21.1.0"
```

**Comment by wfhm** [comment]
@enricoantonini84

Google removed Firebase Instance ID API from firebase-messaging:22.0.0, and it breaks our SDK. As a workaround, you can use the solution proposed by Google and @YarikSOffice - just add firebase-iid dependency explicitly:

    implementation "com.google.firebase:firebase-iid:21.1.0"

More details here:

https://firebase.google.com/support/release-notes/android#messaging_v22-0-0

**Comment by bryanoptus** [comment]
We're facing the same issue as well. Would be great if this could be sorted in an upcoming release soon.

**Comment by elliemehrganrad** [comment]
We have the same issue updating to FCM 22.0.0.

**Comment by enricoantonini84** [comment]
The @YarikSOffice solution works fine, but should be solved directly by Pushwoosh by including FCM 22 dependency in their libraries.

**Comment by wfhm** [comment]
@enricoantonini84 @bryanoptus @YariksOffice

Fixed in 6.3.0.
