### ISSUE TITLE
NoClassDefFoundError in version 3.1.0

### ISSUE THREAD

**Issue by IlyaDvoinoi** [Pushwoosh/pushwoosh-android-sdk#17]
Hellow! After migrate to new version (use this guide - http://docs.pushwoosh.com/docs/android-sdk-fragments), get error (Device Sony C6503, Android 4.4.4)

08-18 17:45:06.720  12366-12366/? E/Parcel﹕ Class not found when unmarshalling: com.google.android.gms.iid.MessengerCompat
    java.lang.ClassNotFoundException: com.google.android.gms.iid.MessengerCompat
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:251)
            at android.os.Parcel.readParcelableCreator(Parcel.java:2165)
            at android.os.Parcel.readParcelable(Parcel.java:2129)
            at android.os.Parcel.readValue(Parcel.java:2045)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2346)
            at android.os.Bundle.unparcel(Bundle.java:249)
            at android.os.Bundle.containsKey(Bundle.java:299)
            at android.content.Intent.hasExtra(Intent.java:4456)
            at com.pushwoosh.thirdparty.gms.iid.zzc.zze(Unknown Source)
            at com.pushwoosh.thirdparty.gms.iid.zzc$1.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:212)
            at android.app.ActivityThread.main(ActivityThread.java:5135)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NoClassDefFoundError: com/google/android/gms/iid/MessengerCompat
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:251)
            at android.os.Parcel.readParcelableCreator(Parcel.java:2165)
            at android.os.Parcel.readParcelable(Parcel.java:2129)
            at android.os.Parcel.readValue(Parcel.java:2045)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2346)
            at android.os.Bundle.unparcel(Bundle.java:249)
            at android.os.Bundle.containsKey(Bundle.java:299)
            at android.content.Intent.hasExtra(Intent.java:4456)
            at com.pushwoosh.thirdparty.gms.iid.zzc.zze(Unknown Source)
            at com.pushwoosh.thirdparty.gms.iid.zzc$1.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:212)
            at android.app.ActivityThread.main(ActivityThread.java:5135)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.MessengerCompat" on path: DexPathList[[zip file "/data/app/com.rwgg.reworld-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.rwgg.reworld-2, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:251)
            at android.os.Parcel.readParcelableCreator(Parcel.java:2165)
            at android.os.Parcel.readParcelable(Parcel.java:2129)
            at android.os.Parcel.readValue(Parcel.java:2045)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2346)
            at android.os.Bundle.unparcel(Bundle.java:249)
            at android.os.Bundle.containsKey(Bundle.java:299)
            at android.content.Intent.hasExtra(Intent.java:4456)
            at com.pushwoosh.thirdparty.gms.iid.zzc.zze(Unknown Source)
            at com.pushwoosh.thirdparty.gms.iid.zzc$1.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:212)
            at android.app.ActivityThread.main(ActivityThread.java:5135)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
            at dalvik.system.NativeStart.main(Native Method)
08-18 17:45:06.720  12366-12366/? W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x4163fd88)
08-18 17:45:06.941  12366-12366/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.rwgg.reworld, PID: 12366
    android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.iid.MessengerCompat
            at android.os.Parcel.readParcelableCreator(Parcel.java:2179)
            at android.os.Parcel.readParcelable(Parcel.java:2129)
            at android.os.Parcel.readValue(Parcel.java:2045)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2346)
            at android.os.Bundle.unparcel(Bundle.java:249)
            at android.os.Bundle.containsKey(Bundle.java:299)
            at android.content.Intent.hasExtra(Intent.java:4456)
            at com.pushwoosh.thirdparty.gms.iid.zzc.zze(Unknown Source)
            at com.pushwoosh.thirdparty.gms.iid.zzc$1.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:212)
            at android.app.ActivityThread.main(ActivityThread.java:5135)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by shaders** [comment]
You can try the new build (3.1.2). Please also check the android updated guides as you need to change Android Manifest (again, sorry):
http://docs.pushwoosh.com/docs/androidmanifestxml-modifications

and Add Google Play Services LIbrary and Android Support v4.
http://docs.pushwoosh.com/docs/native-android-sdk
