### ISSUE TITLE
NullPointerException when launching app on Android 12

### ISSUE THREAD

**Issue by ronaldsantos63** [Pushwoosh/pushwoosh-android-sdk#177]
Hi,
We are migrating our app to Android 12, but the app crashes when starting.

```
2022-02-03 21:51:45.599 12700-12749/com.gigigo.ipirangaconectcar.dev E/Pushwoosh: [StatusBarNotificationStorageHelper] Failed to update notification storage: Attempt to invoke virtual method 'com.pushwoosh.internal.utils.c com.pushwoosh.PushwooshPlatform.c()' on a null object reference
2022-02-03 21:51:45.612 12700-12749/com.gigigo.ipirangaconectcar.dev E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.gigigo.ipirangaconectcar.dev, PID: 12700
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
        at com.pushwoosh.repository.y.a(Unknown Source:29)
        at com.pushwoosh.repository.RepositoryModule$a.a(Unknown Source:12)
        at com.pushwoosh.repository.RepositoryModule$a.doInBackground(Unknown Source:2)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
```

we are using version 6.4.0

**Comment by wfhm** [comment]
@ronaldsantos63 Got it reproduced, the fix will be rolled out shortly.

**Comment by wfhm** [comment]
@ronaldosantos63 Fixed with the 6.4.1 release.
