### ISSUE TITLE
Application not found

### ISSUE THREAD

**Issue by vlad1m1r990** [Pushwoosh/pushwoosh-android-sdk#19]
I am getting following exception in all of my apps on request https://cp.pushwoosh.com/json/1.3/registerUser
But request https://cp.pushwoosh.com/json/1.3/registerDevice is working ok.

 java.lang.Exception: {"status_code":210,"status_message":"Application not found"}
            at com.pushwoosh.internal.request.RequestManager.sendRequestSync(Unknown Source)
            at com.pushwoosh.PushManager.registerUserInternal(Unknown Source)
            at com.pushwoosh.PushManager.access$000(Unknown Source)
            at com.pushwoosh.PushManager$1.run(Unknown Source)

**Comment by DimanAM** [comment]
"registerUser" is used only for In-App Messages (http://docs.pushwoosh.com/docs/in-app-messages). 
You can ignore this exception (it does not affect anything) if you don't use this feature.

**Comment by DimanAM** [comment]
Fixed
