### ISSUE TITLE
Richpage issues with Android 6.0

### ISSUE THREAD

**Issue by charvel02** [Pushwoosh/pushwoosh-android-sdk#24]
Have you tested Richpage pushes on Android 6.0? I am getting exception errors when trying to open richpage notifications on devices running 6.0. (exact version is 6.0.1). It is working on devices running 4.1 and 5.0. Running Pushwoosh version 3.2.0. Stack trace below.

12-14 10:02:45.313 12344-12361/I/Pushwoosh: [com.pushwoosh.GCMListenerService] Received message: Bundle[{pw_msg=1, j=1137, p=1S, ibc=#ff0000, pri=, vib=0, title=new content!, collapse_key=do_not_collapse}] from: 368319224253
12-14 10:02:45.324 12344-12361/ I/Pushwoosh: [AbsNotificationFactory] nofify: Bundle[{onStart=false, pw_msg=1, j=1137, p=1S, ibc=#ff0000, pri=, vib=0, title=new content!, collapse_key=do_not_collapse, foreground=true}]
12-14 10:02:46.331 12344-12366/D/Pushwoosh: [RequestManager] Try To send: messageDeliveryEvent
12-14 10:02:46.552 12344-12366/ I/Pushwoosh: [RequestManager] 
                                                               x
                                                               |     Pushwoosh request:
                                                               | Url: https://cp.pushwoosh.com/json/1.3/messageDeliveryEvent
                                                               | Payload: {"request":{"v":"3.2.0.614","device_type":3,"application":"57468-3DE96","hwid":"cbaf71b9a4e07f2c","hash":"1S","userId":"cbaf71b9a4e07f2c"}}
                                                               | Response: {"status_code":200,"status_message":"OK","response":null}
                                                               x
12-14 10:02:46.552 12344-12366/ D/Pushwoosh: [RequestManager] messageDeliveryEvent response success
12-14 10:02:48.215 12344-12428/ D/Pushwoosh: [RequestManager] Try To send: getPage
12-14 10:02:48.421 12344-12428/ I/Pushwoosh: [RequestManager] 
                                                               x
                                                               |     Pushwoosh request:
                                                               | Url: https://cp.pushwoosh.com/json/1.3/getPage
                                                               | Payload: {"request":{"v":"3.2.0.614","device_type":3,"page_id":"1137","application":"57468-3DE96","hwid":"cbaf71b9a4e07f2c","userId":"cbaf71b9a4e07f2c"}}
                                                               | Response: {"status_code":200,"status_message":"OK","response":{"page":{"1":{"background":"255,255,255,255","headerBackground":"255,0,0,255","name":"global","type":"global","formHeader":"Global Settings"},"2":{"content":"&lt; Back","color":"255,255,255,255","name":"backBtn","type":"backBtn","formHeader":"Button Back"},"3":{"url":"https:\/\/cp.pushwoosh.com\/img\/logo.png","name":"logo","type":"img","formHeader":"Logo"},"4":{"content":"<p>Pushwoosh<\/p>","fontSize":"32","color":"255,255,255,255","name":"title","type":"lineText","formHeader":"Title"},"5":{"url":"https:\/\/cp.pushwoosh.com\/img\/logo-large.png","name":"banner","type":"img","formHeader":"Banner"},"6":{"content":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","fontSize":"14","color":"#fff","name":"content","type":"blockText","formHeader":"Text Content"},"7":{"background":"0,20,77,255","backgroundHover":"19,36,83,255","content":"Submit","color":"255,255,255,255","url":"","json":"","name":"submitBtn","type":"btn","formHeader":"Button Submit"}},"template":"1"}}
                                                               x
12-14 10:02:48.421 12344-12428/ D/Pushwoosh: [RequestManager] getPage response success
12-14 10:02:48.802 12344-12344/ E/Pushwoosh: Exception ocurred
                                                               java.lang.IllegalAccessException: java.lang.Class<android.content.res.XmlBlock> is not accessible from java.lang.Class<com.pushwoosh.richpages.RichPushUtils>
                                                                   at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                   at com.pushwoosh.richpages.RichPushUtils.getParser(Unknown Source)
                                                                   at com.pushwoosh.richpages.RichPageActivity.getInflatedView(Unknown Source)
                                                                   at com.pushwoosh.richpages.RichPageActivity.addView(Unknown Source)
                                                                   at com.pushwoosh.richpages.RichPageActivity.onPageLoadSuccess(Unknown Source)
                                                                   at com.pushwoosh.richpages.RichPageActivity$GetPageTask.onPostExecute(Unknown Source)
                                                                   at com.pushwoosh.richpages.RichPageActivity$GetPageTask.onPostExecute(Unknown Source)
                                                                   at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                   at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-14 10:02:48.808 12344-12344/ D/AndroidRuntime: Shutting down VM
12-14 10:02:48.813 12344-12344/ E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: , PID: 12344
                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.xmlpull.v1.XmlPullParser.getPositionDescription()' on a null object reference
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:540)
                                                                        at com.pushwoosh.richpages.RichPageActivity.getInflatedView(Unknown Source)
                                                                        at com.pushwoosh.richpages.RichPageActivity.addView(Unknown Source)
                                                                        at com.pushwoosh.richpages.RichPageActivity.onPageLoadSuccess(Unknown Source)
                                                                        at com.pushwoosh.richpages.RichPageActivity$GetPageTask.onPostExecute(Unknown Source)
                                                                        at com.pushwoosh.richpages.RichPageActivity$GetPageTask.onPostExecute(Unknown Source)
                                                                        at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                        at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-14 10:02:49.181 12344-12366/ D/Pushwoosh: [RequestManager] Try To send: pushStat
12-14 10:02:49.383 12344-12366/ I/Pushwoosh: [RequestManager] 
                                                               x
                                                               |     Pushwoosh request:
                                                               | Url: https://cp.pushwoosh.com/json/1.3/pushStat
                                                               | Payload: {"request":{"v":"3.2.0.614","device_type":3,"application":"57468-3DE96","hwid":"cbaf71b9a4e07f2c","hash":"1S","userId":"cbaf71b9a4e07f2c"}}
                                                               | Response: {"status_code":200,"status_message":"OK","response":null}
                                                               x
12-14 10:02:49.384 12344-12366/ D/Pushwoosh: [RequestManager] pushStat response success

**Comment by shaders** [comment]
Checking
