### ISSUE TITLE
Unmarshalling unknown type code

### ISSUE THREAD

**Issue by vlad1m1r990** [Pushwoosh/pushwoosh-android-sdk#36]
Since update to 4.+ version (from 3.+) I am getting this error message.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app/com.pushwoosh.PushHandlerActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@d3fa3ae: Unmarshalling unknown type code 6881384 at offset 4944
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.RuntimeException: Parcel android.os.Parcel@d3fa3ae: Unmarshalling unknown type code 6881384 at offset 4944
       at android.os.Parcel.readValue(Parcel.java:2340)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.BaseBundle.getBoolean(BaseBundle.java:659)
       at com.pushwoosh.internal.PushManagerImpl.preHandlePush(PushManagerImpl.java:102)
       at com.pushwoosh.internal.PushManagerImpl.onHandlePush(PushManagerImpl.java:59)
       at com.pushwoosh.PushHandlerActivity.handlePush(PushHandlerActivity.java:29)
       at com.pushwoosh.PushHandlerActivity.onCreate(PushHandlerActivity.java:24)
       at android.app.Activity.performCreate(Activity.java:6251)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by shaders** [comment]
What kind of content do you send along with push notification?

**Comment by vlad1m1r990** [comment]
We are sending message content and small JSON in Custom Data. 
JSON format is: {"type":1, "url":"https://www.url.com","image":"http://imageurl.com/xyz.jpg"}

**Comment by shaders** [comment]
Could you please try version  4.1.3 (recently published)?

**Comment by vlad1m1r990** [comment]
I will upgrade library for next build, but since I can't reproduce the bug I will know is it fixed when new version goes  live (in 2 weeks).
