### ISSUE TITLE
java.lang.NoClassDefFoundError: com/amazon/device/messaging/ADMMessageReceiver

### ISSUE THREAD

**Issue by TechIsFun** [Pushwoosh/pushwoosh-android-sdk#41]
If you try to run Robolectric tests, you'll get this exception:

``` java
java.lang.NoClassDefFoundError: com/amazon/device/messaging/ADMMessageReceiver
    at java.lang.ClassLoader.defineClass1(Native Method)
     at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
     at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
     at org.robolectric.internal.bytecode.InstrumentingClassLoader.findClass(InstrumentingClassLoader.java:153)
     at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:95)
     at java.lang.Class.forName0(Native Method)
     at java.lang.Class.forName(Class.java:264)
     at org.robolectric.internal.Shadow.newInstanceOf(Shadow.java:15)
     at org.robolectric.shadows.ShadowApplication.registerBroadcastReceivers(ShadowApplication.java:148)
     at org.robolectric.shadows.ShadowApplication.bind(ShadowApplication.java:137)
     at org.robolectric.shadows.CoreShadowsAdapter.bind(CoreShadowsAdapter.java:99)
     at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:121)
     at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
     at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
     at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
     at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
     at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
     at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
     at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:497)
     at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
     Caused by: java.lang.ClassNotFoundException: com.amazon.device.messaging.ADMMessageReceiver
     at org.robolectric.internal.bytecode.InstrumentingClassLoader.getByteCode(InstrumentingClassLoader.java:168)
     at org.robolectric.internal.bytecode.InstrumentingClassLoader.findClass(InstrumentingClassLoader.java:123)
     at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:95)
     ... 32 more
```

Robolectric version: 3.0
Pushwoosh version:  4.6.1

Workaround: 
In your test forlder create a package `com.amazon.device.messaging` with two classes:

``` java
public class ADMMessageHandlerBase {
}

public class ADMMessageReceiver extends android.content.BroadcastReceiver {

    public ADMMessageReceiver(Class<?> clazz) {

    }

    @Override
    public void onReceive(Context context, Intent intent) {

    }
}
```

**Comment by dfpalomar** [comment]
@TechIsFun thanks for the workaround ;-)
