### ISSUE TITLE
StringIndexOutOfBoundsException on version 4.12.2 after 5.0 sdk update

### ISSUE THREAD

**Issue by justixLoL** [Pushwoosh/pushwoosh-android-sdk#56]
Hi,
I stay on PushWoosh SDK 4.12.2 when u released 5.0 version and now i get exception

Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=1
at java.lang.String.substring(String.java:1897)
at com.pushwoosh.internal.utils.a.<init>(Unknown Source)
 at com.pushwoosh.internal.utils.a.a(Unknown Source)
at com.pushwoosh.fragment.PushFragment.registerReceivers(Unknown Source)
at com.pushwoosh.fragment.PushFragment.register(Unknown Source)
at com.pushwoosh.fragment.PushFragment.onCreate(Unknown Source)

I don't want to update to 5.0 version, can i fix it somehow?

**Comment by shaders** [comment]
It looks like there's something wrong in the AndroidManifest.xml

The SDK weren't able to find this tag:
&lt;meta-data android:name="com.pushwoosh.senderid" android:value="A123456789012" /&gt;

It is not a reason for a crash of course and this will be fixed.
Could you please check your AndroidManifest.xml for com.pushwoosh.senderid value?

**Comment by justixLoL** [comment]
I did it, but it didnt help
Just remeber that i have 4.12.2 version
And there was in Manifest:
<meta-data android:name="PW_APPID" android:value="@string/PW_APPID" />
<meta-data android:name="PW_PROJECT_ID" android:value="@string/PW_PROJECT_ID" />
PW_APPID and PW_PROJECT_ID keys, not com.pushwoosh.senderid...

**Comment by justixLoL** [comment]
Close issue
I don't feel @string/PW_APPID and @string/PW_PROJECT_ID for flavors i build app with , sry
