### ISSUE TITLE
Pushwoosh.getInstance() error

### ISSUE THREAD

**Issue by ahmtkocamn** [Pushwoosh/pushwoosh-android-sdk#57]
07-06 17:48:17.257 3532-3532/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.turkburo.sen, PID: 3532
                                                 java.lang.ExceptionInInitializerError
                                                     at com.turkburo.sen.PushwooshSampleApp.onCreate(PushwooshSampleApp.java:21)
                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                     at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.pushwoosh.notification.j com.pushwoosh.c.d()' on a null object reference
                                                     at com.pushwoosh.Pushwoosh.<init>(Unknown Source)
                                                     at com.pushwoosh.Pushwoosh.<clinit>(Unknown Source)
                                                     at com.turkburo.sen.PushwooshSampleApp.onCreate(PushwooshSampleApp.java:21) 
                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013) 
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707) 
                                                     at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by wfhm** [comment]
Hi,

Could you please specify an Android version of a device on which you get this issue as well as provide us with your AndroidManifest.xml and your app's *build.gradle*?

**Comment by shromyak** [comment]
In my case this crash is correlated with LeakCanary.
Steps to reproduce:
Launch app with deep linking (Airbnb DeepLink) -> Pause deep linked activity (or navigate to another) -> Crash
After removing LeakCanary initialization from application class onCreate method -- crash disappears

**Comment by Zellius** [comment]
Same here.

 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.pushwoosh.notification.e com.pushwoosh.c.d()' on a null object reference
                                                                                 at com.pushwoosh.Pushwoosh.<init>(Unknown Source)
                                                                                 at com.pushwoosh.Pushwoosh.<clinit>(Unknown Source)
                                                                                 at com.pushwoosh.Pushwoosh.getInstance(Unknown Source) 

Used:
**compile 'com.pushwoosh:pushwoosh:5.0.1'**.
**compile 'com.yandex.android:mobmetricalib:2.62'**

I get the Exception after I have invoked _getInstance_ method in the onCreate of my MultiDexApplication class. If I remove YandexMetrica.activate invocation from there all will be fine. But I do not want to remove it :)

Repeated on Android 6+ devices and emulators. Mybe on lower versions too, I did not test this.

**Comment by wfhm** [comment]
Hi,

Turned out it is not a bug of Pushwoosh SDK.This is a peculiarity of multi-processor applications in Android apps environment. 

When you integrate analytics tools such as LeakCanary, AppMetrica and others, these libraries start a new process for itself. A new instance of the app is created In this process. But you do not need to listen for pushes in this separate process, so by default you should not  call `registerForPushNotifications` inside `Application.onCreate()`.

Therefore there are 2 possible solutions:

1) Not to call `registerForPushNotifications` inside `Application.onCreate()`

2) If you want to call `registerForPushNotifications` inside `Application.onCreate()`, you should perform a check in application's main process:

```
List < ActivityManager.RunningAppProcessInfo > runningAppProcesses = ((ActivityManager) getSystemService(Context.ACTIVITY_SERVICE)).getRunningAppProcesses();
if (runningAppProcesses != null && runningAppProcesses.size() != 0) {
 for (ActivityManager.RunningAppProcessInfo runningAppProcessInfo: runningAppProcesses) {
  boolean isCurrentProcess = runningAppProcessInfo.pid == android.os.Process.myPid();
  boolean isMainProcessName = getPackageName().equals(runningAppProcessInfo.processName);
  if (isCurrentProcess && isMainProcessName) {
   Pushwoosh.getInstance().registerForPushNotifications(...);
   break;
  }
 }
}
```
