### ISSUE TITLE
suddenly when run my app integrated with pushwoosh i got crash 

### ISSUE THREAD

**Issue by msalama-ihorizons** [Pushwoosh/pushwoosh-android-sdk#63]
suddenly when run my app integrated with pushwoosh i got crash, when app open

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pushwoosh/PushwooshService;

**Comment by wfhm** [comment]
Hi,

Checking this.

**Comment by msalama-ihorizons** [comment]
Hi,

here is the full exception 

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pushwoosh/PushwooshService;
                                                                       at com.pushwoosh.k.a(Unknown Source)
                                                                       at com.pushwoosh.internal.registrar.a$a.a(Unknown Source)
                                                                       at com.pushwoosh.internal.registrar.a.registerPW(Unknown Source)
                                                                       at com.pushwoosh.notification.e.a(Unknown Source)
                                                                       at com.pushwoosh.Pushwoosh.registerForPushNotifications(Unknown Source)
                                                                       at qa.ooredoo.android.MainActivity.registerPushwoosh(MainActivity.java:697)
                                                                       at qa.ooredoo.android.MainActivity.onCreate(MainActivity.java:222)
                                                                       at android.app.Activity.performCreate(Activity.java:6682)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                    Caused by: java.lang.ClassNotFoundException: com.pushwoosh.PushwooshService
                                                                       at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                       at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                       at com.pushwoosh.k.a(Unknown Source) 
                                                                       at com.pushwoosh.internal.registrar.a$a.a(Unknown Source) 
                                                                       at com.pushwoosh.internal.registrar.a.registerPW(Unknown Source) 
                                                                       at com.pushwoosh.notification.e.a(Unknown Source) 
                                                                       at com.pushwoosh.Pushwoosh.registerForPushNotifications(Unknown Source) 
                                                                       at qa.ooredoo.android.MainActivity.registerPushwoosh(MainActivity.java:697) 
                                                                       at qa.ooredoo.android.MainActivity.onCreate(MainActivity.java:222) 
                                                                       at android.app.Activity.performCreate(Activity.java:6682) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/JobIntentService;
                                                                       at com.pushwoosh.k.a(Unknown Source) 
                                                                       at com.pushwoosh.internal.registrar.a$a.a(Unknown Source) 
                                                                       at com.pushwoosh.internal.registrar.a.registerPW(Unknown Source) 
                                                                       at com.pushwoosh.notification.e.a(Unknown Source) 
                                                                       at com.pushwoosh.Pushwoosh.registerForPushNotifications(Unknown Source) 
                                                                       at qa.ooredoo.android.MainActivity.registerPushwoosh(MainActivity.java:697) 
                                                                       at qa.ooredoo.android.MainActivity.onCreate(MainActivity.java:222) 
                                                                       at android.app.Activity.performCreate(Activity.java:6682) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.JobIntentService" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/qa.ooredoo.android-1/base.apk"],nativeLibraryDirectories=[/data/app/qa.ooredoo.android-1/lib/arm64, /data/app/qa.ooredoo.android-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                       at com.pushwoosh.k.a(Unknown Source) 
                                                                       at com.pushwoosh.internal.registrar.a$a.a(Unknown Source) 
                                                                       at com.pushwoosh.internal.registrar.a.registerPW(Unknown Source) 
                                                                       at com.pushwoosh.notification.e.a(Unknown Source) 
                                                                       at com.pushwoosh.Pushwoosh.registerForPushNotifications(Unknown Source) 
                                                                       at qa.ooredoo.android.MainActivity.registerPushwoosh(MainActivity.java:697) 
                                                                       at qa.ooredoo.android.MainActivity.onCreate(MainActivity.java:222) 
                                                                       at android.app.Activity.performCreate(Activity.java:6682) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by wfhm** [comment]
Make sure your project build.gradle has the following lines:

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}

In your app build.gradle use the following version for compileSdkVersion and buildToolsVersion:

compileSdkVersion 26
buildToolsVersion "26.0.1"
	
Also, all support libraries should be 26.+:

compile 'com.android.support:support-v4:26.+'
compile 'com.android.support:support-v13:26.+'
compile 'com.android.support:design:26.+'
compile 'com.android.support:recyclerview-v7:26.+'

**Comment by msalama-ihorizons** [comment]
Hi,
 Sorry for my late reply. but i added the new android support library as your post and it is working now.

Thank you so much ......
