### ISSUE TITLE
Pushwoosh error on upgrading to Android O

### ISSUE THREAD

**Issue by SahanaRamesh** [Pushwoosh/pushwoosh-android-sdk#67]
Getting error on upgrading the Android version to 26. 
Please find the logs below:
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pushwoosh/PushwooshService;
                                                                      at com.pushwoosh.k.a(Unknown Source)
                                                                      at com.pushwoosh.internal.registrar.a$a.a(Unknown Source)
                                                                      at com.pushwoosh.internal.registrar.a.registerPW(Unknown Source)
                                                                      at com.pushwoosh.notification.e.a(Unknown Source)
                                                                      at com.pushwoosh.Pushwoosh.registerForPushNotifications(Unknown Source)

   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.PushwooshService" on path: DexPathLis

     	Suppressed: java.lang.NoClassDefFoundError: com.pushwoosh.PushwooshService
                                                                      at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                      at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                      at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                      at dalvik.system.DexPathList.findClass(DexPathList.java:338)
                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                      		... 21 more
                                                                  	Suppressed: java.lang.ClassNotFoundException: com.pushwoosh.PushwooshService
                                                                      at java.lang.Class.classForName(Native Method)
                                                                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                      		... 20 more
                                                                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

Android Studio version used: 2.3.3

I have followed the resolution provided for issue no 63, but still facing the same issue. 
Please help.

**Comment by wfhm** [comment]
Hi,

Could you please share your project build.gradle and your app build.gradle?

**Comment by wfhm** [comment]
@SahanaRamesh 

Any news?
