### ISSUE TITLE
ClassNotFoundException in NotificationReceiver

### ISSUE THREAD

**Issue by EstebanC02** [Pushwoosh/pushwoosh-android-sdk#70]
When I start the application, it generates an error message that does not find the Receiver class. I attach the log generated. By performing an identical check I identify that the error occurs when using Proguard.

`E/Pushwoosh: Exception occurred
                                              java.lang.ClassNotFoundException: com.civico.app.data.receiver.PushwooshNotificationReceiver
                                                  at java.lang.Class.classForName(Native Method)
                                                  at java.lang.Class.forName(Class.java:309)
                                                  at java.lang.Class.forName(Class.java:273)
                                                  at com.pushwoosh.a.a(Unknown Source)
                                                  at com.pushwoosh.a.<init>(Unknown Source)
                                                  at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source)
                                                  at android.content.ContentProvider.attachInfo(ContentProvider.java:1696)
                                                  at android.content.ContentProvider.attachInfo(ContentProvider.java:1671)
                                                  at android.app.ActivityThread.installProvider(ActivityThread.java:5084)
                                                  at android.app.ActivityThread.installContentProviders(ActivityThread.java:4679)
                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4619)
                                                  at android.app.ActivityThread.access$1500(ActivityThread.java:155)
                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                  at android.os.Looper.loop(Looper.java:135)
                                                  at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "com.civico.app.data.receiver.PushwooshNotificationReceiver" on path: DexPathList[[zip file "/data/app/com.civico.app.beta-1/base.apk"],nativeLibraryDirectories=[/data/app/com.civico.app.beta-1/lib/arm, /vendor/lib, /system/lib]]
                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                  at java.lang.Class.classForName(Native Method) 
                                                  at java.lang.Class.forName(Class.java:309) 
                                                  at java.lang.Class.forName(Class.java:273) 
                                                  at com.pushwoosh.a.a(Unknown Source) 
                                                  at com.pushwoosh.a.<init>(Unknown Source) 
                                                  at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source) 
                                                  at android.content.ContentProvider.attachInfo(ContentProvider.java:1696) 
                                                  at android.content.ContentProvider.attachInfo(ContentProvider.java:1671) 
                                                  at android.app.ActivityThread.installProvider(ActivityThread.java:5084) 
                                                  at android.app.ActivityThread.installContentProviders(ActivityThread.java:4679) 
                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4619) 
                                                  at android.app.ActivityThread.access$1500(ActivityThread.java:155) 
                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                  at android.os.Looper.loop(Looper.java:135) 
                                                  at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
                                              	Suppressed: java.lang.ClassNotFoundException: com.civico.app.data.receiver.PushwooshNotificationReceiver
                                                  at java.lang.Class.classForName(Native Method)
                                                  at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                  at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                  		... 21 more
                                               Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
10-03 21:39:46.600 32629-32629/com.civico.app.beta D/AndroidRuntime: Shutting down VM
10-03 21:39:46.601 32629-32629/com.civico.app.beta E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.civico.app.beta, PID: 32629
                                                                     java.lang.RuntimeException: Unable to get provider com.pushwoosh.PushwooshInitProvider: java.lang.IllegalStateException: Could not find class for name: com.civico.app.data.receiver.PushwooshNotificationReceiver
                                                                         at android.app.ActivityThread.installProvider(ActivityThread.java:5087)
                                                                         at android.app.ActivityThread.installContentProviders(ActivityThread.java:4679)
                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4619)
                                                                         at android.app.ActivityThread.access$1500(ActivityThread.java:155)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                      Caused by: java.lang.IllegalStateException: Could not find class for name: com.civico.app.data.receiver.PushwooshNotificationReceiver
                                                                         at com.pushwoosh.a.a(Unknown Source)
                                                                         at com.pushwoosh.a.<init>(Unknown Source)
                                                                         at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source)
                                                                         at android.content.ContentProvider.attachInfo(ContentProvider.java:1696)
                                                                         at android.content.ContentProvider.attachInfo(ContentProvider.java:1671)
                                                                         at android.app.ActivityThread.installProvider(ActivityThread.java:5084)
                                                                         at android.app.ActivityThread.installContentProviders(ActivityThread.java:4679) 
                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4619) 
                                                                         at android.app.ActivityThread.access$1500(ActivityThread.java:155) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5343)`

AndroidManifest:

`<meta-data
            android:name="com.pushwoosh.notification_service_extension"
            android:value="com.civico.app.data.receiver.PushwooshNotificationReceiver" />`

Gradle:

`implementation 'com.pushwoosh:pushwoosh:5.1.1'`
`implementation 'com.pushwoosh:pushwoosh-badge:5.1.1'`
`implementation 'com.pushwoosh:pushwoosh-location:5.1.1'`
`implementation 'com.pushwoosh:pushwoosh-beacon:5.1.1'`

**Comment by wfhm** [comment]
Hi,

Please try adding `-keep class com.civico.app.data.receiver.PushwooshNotificationReceiver  {*;}` to prevent obfuscating Pushwoosh classes. It uses reflection in a build process, so, if obfuscated, might lead to this error.

**Comment by EstebanC02** [comment]
Hi, 

Thank you for your quick response. That was the problem. Thank you!
