### ISSUE TITLE
[RequestManager] ERROR: Unable to resolve host

### ISSUE THREAD

**Issue by EstebanC02** [Pushwoosh/pushwoosh-android-sdk#71]
By opening my debug application the following error occurred that does not allow me to start the application, it closes before starting the splash:

`E/Pushwoosh: [RequestManager] ERROR: Unable to resolve host "2CCDB-721B0.api.pushwoosh.com": No address associated with hostname
                                          com.pushwoosh.internal.network.b: Unable to resolve host "2CCDB-721B0.api.pushwoosh.com": No address associated with hostname
                                              at com.pushwoosh.internal.network.d.a(Unknown Source)
                                              at com.pushwoosh.internal.network.d.sendRequestSync(Unknown Source)
                                              at com.pushwoosh.inapp.InAppRetrieverService.onHandleWork(Unknown Source)
                                              at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
                                              at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
                                              at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                              at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                              at java.lang.Thread.run(Thread.java:856)`

build.gradle

`implementation 'com.pushwoosh:pushwoosh:5.1.1'`
`implementation 'com.pushwoosh:pushwoosh-badge:5.1.1'`
`implementation 'com.pushwoosh:pushwoosh-location:5.1.1'`
`implementation 'com.pushwoosh:pushwoosh-beacon:5.1.1'`

**Comment by EstebanC02** [comment]
The bug shows only in the very first start

**Comment by wfhm** [comment]
Hi,

It looks like a connection issue. Is the issue reproducible or had it occurred just once? Also, it does not look like a crash, so could you please check whether there is anything else in the log what might explain why your app closes?
