### ISSUE TITLE
[PushwooshLocation] [LocationTracker] connection failed

### ISSUE THREAD

**Issue by EstebanC02** [Pushwoosh/pushwoosh-android-sdk#72]
By opening my debug application the following error occurred that does not allow me to start the application, it closes before starting the splash

```
E/Pushwoosh: [PushwooshLocation] [LocationTracker] connection failed: ConnectionResult.getErrorCode() = 9

E/Pushwoosh: Exception occurred
                                          com.pushwoosh.location.network.exception.LocationNotAvailableException: Location not found
                                              at com.pushwoosh.location.network.b.d.a(Unknown Source)
                                              at com.pushwoosh.location.network.c.a.a(Unknown Source)
                                              at com.pushwoosh.location.network.a.a(Unknown Source)
                                              at com.pushwoosh.location.network.GeoLocationServiceApi16.onHandleWork(Unknown Source)
                                              at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
                                              at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
                                              at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                              at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                              at java.lang.Thread.run(Thread.java:856)
```

SplashActivity

`PushwooshLocation.startLocationTracking();`

build.gradle

`implementation 'com.pushwoosh:pushwoosh:5.1.1'`
`implementation 'com.pushwoosh:pushwoosh-badge:5.1.1'`
`implementation 'com.pushwoosh:pushwoosh-location:5.1.1'`
`implementation 'com.pushwoosh:pushwoosh-beacon:5.1.1'`

**Comment by EstebanC02** [comment]
The bug shows only in the very first start

**Comment by wfhm** [comment]
Hi,

Checking this.

**Comment by wfhm** [comment]
ConnectionResult.getErrorCode() = 9 indicates that outdated version of Google Play services libs is used in your project:

https://developers.google.com/android/reference/com/google/android/gms/common/ConnectionResult.html#SERVICE_INVALID

The stacktrace you have shared could not be the reason for a crash, it only indicates that device location could not be found. 

The issue should be somewhere else. Could you please share a full log?

**Comment by wfhm** [comment]
@EstebanC02 Is there any update on this issue?

**Comment by EstebanC02** [comment]
Works with the new version. Thanks!
