### ISSUE TITLE
Network exceptions are not handled properly and have a security flaw

### ISSUE THREAD

**Issue by n-belokopytov** [Pushwoosh/pushwoosh-android-sdk#77]
When trying to register with a callback in PW 5.1.1 SDK, the  exception is just logged into logcat. It exposes the application's <pushwoosh_app_key> while doing so, which IMO is not very secure. Moreover, this exception is not handled as a Result and therefore doesn't trigger the "registration is unsuccessful" branch in the callback. The callback gets skipped completely.

`
10-18 10:33:02.864 31573-31777/com.getyourguide.android.debug D/Pushwoosh: [RequestManager] Try To send: applicationOpen; baseUrl: https://<pushwoosh_app_key>.api.pushwoosh.com/json/1.3/
10-18 10:33:03.041 31573-31777/com.getyourguide.android.debug E/Pushwoosh: [RequestManager] ERROR: Unable to resolve host "<pushwoosh_app_key>.api.pushwoosh.com": No address associated with hostname
                                                                           com.pushwoosh.internal.network.b: Unable to resolve host "<pushwoosh_app_key>.api.pushwoosh.com": No address associated with hostname
                                                                               at com.pushwoosh.internal.network.d.a(Unknown Source)
                                                                               at com.pushwoosh.internal.network.d.a(Unknown Source)
                                                                               at com.pushwoosh.internal.network.d.a(Unknown Source)
                                                                               at com.pushwoosh.internal.network.e.run(Unknown Source)
                                                                               at com.pushwoosh.PushwooshService.onHandleWork(Unknown Source)
                                                                               at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
                                                                               at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                               at java.lang.Thread.run(Thread.java:762)
`

**Comment by wfhm** [comment]
@n-belokopytov 

Thank you for letting us know. Will check it.

**Comment by wfhm** [comment]
@n-belokopytov 

With **NONE** log level and with no internet connection there should be no errors in a device log, so Pushwoosh App ID should not be exposed. Could it be a solution for your case?

Also, the registration callback is independent of applicationOpen - if `registerForPushNotifications` fires, the callback still gets called even if /applicationOpen fails.

**Comment by n-belokopytov** [comment]
@wfhm we prefer to log error-level messages in an obfuscated manner to the log, so that the power users could assist us with debugging.

> Also, the registration callback is independent of applicationOpen - if registerForPushNotifications fires, the callback still gets called even if /applicationOpen fails.

So what you are saying is that it's normal that PW fails here when there is no internet connection and we get no "unsuccessful" result?

**Comment by wfhm** [comment]
@n-belokopytov 

> we prefer to log error-level messages in an obfuscated manner to the log, so that the power users could assist us with debugging.

Got it. This functionality will be added with the upcoming releases.

> So what you are saying is that it's normal that PW fails here when there is no internet connection and we get no "unsuccessful" result?

Could you please elaborate on this one? Which "unsuccessful" result do you want to catch? 

> this exception is not handled as a Result and therefore doesn't trigger the "registration is unsuccessful" branch in the callback. The callback gets skipped completely.

Fail registration callback will fire when Pushwoosh registration fails (when `registerForPushNotifications` fails). `registerForPushNotifications` will still be called, even if applicationOpen and other API methods called on Pushwoosh SDK initialization fail. 

Here's a log extract we got with internet disabled - as you can see, /getInApps (and applicationOpen) fails, throwing an error, still SDK attempts to send /registerDevice and then responds with a registration error.

> 11-21 08:05:45.179 22175-22215/com.example.pushwoosh.testpushproject D/Pushwoosh: [RequestManager] Try To send: getInApps; baseUrl: https://XXXXX-XXXXX.api.pushwoosh.com/json/1.3/
11-21 08:05:45.189 22175-22215/com.example.pushwoosh.testpushproject E/Pushwoosh: [RequestManager] ERROR: Unable to resolve host "XXXXX-XXXXX.api.pushwoosh.com": No address associated with hostname
                                                                                  com.pushwoosh.internal.network.b: Unable to resolve host "B0133-4F712.api.pushwoosh.com": No address associated with hostname
                                                                                      at com.pushwoosh.internal.network.d.a(Unknown Source)
                                                                                      at com.pushwoosh.internal.network.d.sendRequestSync(Unknown Source)
                                                                                      at com.pushwoosh.inapp.d.c.a(Unknown Source)
                                                                                      at com.pushwoosh.inapp.InAppRetrieverService.onHandleWork(Unknown Source)
                                                                                      at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
                                                                                      at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
                                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                      at java.lang.Thread.run(Thread.java:818)
11-21 08:05:45.204 22175-22214/com.example.pushwoosh.testpushproject D/Pushwoosh: [RequestManager] Try To send: registerDevice; baseUrl: https://XXXXX-XXXXX.api.pushwoosh.com/json/1.3/
...
11-21 08:05:45.379 22175-22175/com.example.pushwoosh.testpushproject E/Pushwoosh: [DeviceRegistrar] Registration error: Unable to resolve host "XXXXX-XXXXX.api.pushwoosh.com": No address associated with hostname
