### ISSUE TITLE
ClassNotFoundException after enabled the proguard in my app

### ISSUE THREAD

**Issue by ananth10** [Pushwoosh/pushwoosh-android-sdk#93]
It was working well before. when i enabled the proguard option in my app. the app getting crash.

**Log cat**

12-27 15:19:48.443 13191-13191/com.my.app E/Pushwoosh: Exception occurred
                                                                    java.lang.ClassNotFoundException: com.my.app.android.pushwoosh.PushWooshNotificationService
                                                                        at java.lang.Class.classForName(Native Method)
                                                                        at java.lang.Class.forName(Class.java:400)
                                                                        at java.lang.Class.forName(Class.java:326)
                                                                        at com.pushwoosh.e.a(Unknown Source)
                                                                        at com.pushwoosh.e.<init>(Unknown Source)
                                                                        at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source)
                                                                        at android.content.ContentProvider.attachInfo(ContentProvider.java:1758)
                                                                        at android.content.ContentProvider.attachInfo(ContentProvider.java:1733)
                                                                        at android.app.ActivityThread.installProvider(ActivityThread.java:6326)
                                                                        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5918)
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5857)
                                                                        at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.my.app.android.pushwoosh.PushWooshNotificationService" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.byibyi.tech.adviser-2/base.apk"],nativeLibraryDirectories=[/data/app/com.byibyi.tech.adviser-2/lib/arm64, /data/app/com.byibyi.tech.adviser-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                        at java.lang.Class.classForName(Native Method) 
                                                                        at java.lang.Class.forName(Class.java:400) 
                                                                        at java.lang.Class.forName(Class.java:326) 
                                                                        at com.pushwoosh.e.a(Unknown Source) 
                                                                        at com.pushwoosh.e.<init>(Unknown Source) 
                                                                        at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source) 
                                                                        at android.content.ContentProvider.attachInfo(ContentProvider.java:1758) 
                                                                        at android.content.ContentProvider.attachInfo(ContentProvider.java:1733) 
                                                                        at android.app.ActivityThread.installProvider(ActivityThread.java:6326) 
                                                                        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5918) 
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5857) 
                                                                        at android.app.ActivityThread.-wrap3(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6682) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
12-27 15:19:48.445 13191-13191/com.my.app D/AndroidRuntime: Shutting down VM
12-27 15:19:48.446 13191-13191/com.my.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.my.appr, PID: 13191
                                                                         java.lang.RuntimeException: Unable to get provider com.pushwoosh.PushwooshInitProvider: java.lang.IllegalStateException: Could not find class for name: com.my.app.android.pushwoosh.PushWooshNotificationService
                                                                             at android.app.ActivityThread.installProvider(ActivityThread.java:6329)
                                                                             at android.app.ActivityThread.installContentProviders(ActivityThread.java:5918)
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5857)
                                                                             at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                          Caused by: java.lang.IllegalStateException: Could not find class for name: com.my.app.android.pushwoosh.PushWooshNotificationService
                                                                             at com.pushwoosh.e.a(Unknown Source)
                                                                             at com.pushwoosh.e.<init>(Unknown Source)
                                                                             at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source)
                                                                             at android.content.ContentProvider.attachInfo(ContentProvider.java:1758)
                                                                             at android.content.ContentProvider.attachInfo(ContentProvider.java:1733)
                                                                             at android.app.ActivityThread.installProvider(ActivityThread.java:6326)
                                                                             at android.app.ActivityThread.installContentProviders(ActivityThread.java:5918) 
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5857) 
                                                                             at android.app.ActivityThread.-wrap3(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:154) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6682) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by wfhm** [comment]
Hi,

Please try adding the following lines to your proguard file:

```
-keep class com.pushwoosh.** { *; } 
-dontwarn com.pushwoosh.**
```

**Comment by ananth10** [comment]
Hi @wfhm . i have added those line in my proguard text. but still seeing same error. if i add this 

-keep class * {
    public private *;
}

its working well. but proguard obfuscate not working properly. means package name not converting into a , bb . dd like tat.

**Comment by wfhm** [comment]
@ananth10 

Sorry for the delay. Please try the following one:

```
-keep class com.my.app.android.pushwoosh.PushWooshNotificationService {*;}
```

**Comment by ananth10** [comment]
@wfhm Thanks for quick response. i will try it

**Comment by ananth10** [comment]
@wfhm Thanks for quick response. i will try it

**Comment by ananth10** [comment]
@wfhm I have tried it but getting same exception **"java.lang.ClassNotFoundException: com.my.app.android.pushwoosh.PushWooshNotificationService"**

**Comment by wfhm** [comment]
@ananth10 

Could you please let us know whether you figured out a solution to this issue? Please note that we were unable to reproduce the issue after adding a `-keep class com.my.app.android.pushwoosh.PushWooshNotificationService {*;}` to Proguard settings.

**Comment by ananth10** [comment]
@wfhm I will try it again and let you know it.
