### ISSUE TITLE
Pushwoosh crashes a lot on Android 7.0

### ISSUE THREAD

**Issue by Tunder1992** [Pushwoosh/pushwoosh-android-sdk#95]
Loads of users have the problem that our app crashes because of pushwoosh. Maybe you guys know why. They are all Android 7 users, but no all Android 7 users experience it.

> Fatal Exception: java.lang.ExceptionInInitializerError
       at nl.bigspark.androidplanet.controller.SplashScreen.onCreate(SplashScreen.java:51)
       at android.app.Activity.performCreate(Activity.java:6948)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3042)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6780)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.pushwoosh.notification.e com.pushwoosh.g.d()' on a null object reference
       at com.pushwoosh.Pushwoosh.<init>(Unknown Source)
       at com.pushwoosh.Pushwoosh.<clinit>(Unknown Source)
       at nl.bigspark.androidplanet.controller.SplashScreen.onCreate(SplashScreen.java:51)
       at android.app.Activity.performCreate(Activity.java:6948)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3042)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6780)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by wfhm** [comment]
Could you please specify Pushwoosh SDK version? Also, were you able to reproduce the issue? What are the steps to reproduce it?

**Comment by goncalosilva-appgeneration** [comment]
I'm having the same crashes but I'm using version 5.1.1.
It only happens on Android 7 - mostly Samsung and Huawei devices.

Here's a sample stacktrace from a Huawei P9 Lite:

> Fatal Exception: java.lang.ExceptionInInitializerError
       at org.cocos2dx.cpp.AppActivity.onCreate(AppActivity.java:160)
       at android.app.Activity.performCreate(Activity.java:6910)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.pushwoosh.notification.e com.pushwoosh.g.d()' on a null object reference
       at com.pushwoosh.Pushwoosh.<init>(Unknown Source)
       at com.pushwoosh.Pushwoosh.<clinit>(Unknown Source)
       at org.cocos2dx.cpp.AppActivity.onCreate(AppActivity.java:160)
       at android.app.Activity.performCreate(Activity.java:6910)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by wfhm** [comment]
@goncalosilva-appgeneration Which Pushwoosh version do you use in your project?

**Comment by wfhm** [comment]
@Tunder1992 Updating Pushwoosh SDK to the latest one is essential in further investigation, therefore may I ask you to submit a support ticket at help@pushwoosh.com, so we could assist you with the issues you experience with the latest SDK version?

**Comment by goncalosilva-appgeneration** [comment]
@wfhm We use version 5.1.1 with the GCM integration.

**Comment by Tunder1992** [comment]
Updated Pushwoosh to the latest version. Will keep you updated as soon as we publish the update @wfhm
